/**
 * In-memory TypeORM-shaped repository helpers for OAuth tests.
 *
 * Provides just enough of the `Repository<T>` surface that the
 * `OAuthService` uses (`findOne`, `create`, `save`) so the service
 * can be exercised end-to-end without a real PostgreSQL connection.
 *
 * The arrays passed to `makeRepo` are referenced by the returned repo's
 * methods (no copy is made) — pre-seeding rows from the test body is
 * therefore visible to the service on the same arrays.
 *
 * Shared between the T6 unit suite and the T7 contract test.
 */
import { randomUUID } from 'node:crypto';

import type { User } from '../../../src/entities/User';
import type { UserIdentity } from '../../../src/entities/UserIdentity';

/** In-memory shape of a `User` row. Mirrors the `User` entity's columns. */
export type InMemoryUser = {
  id: string;
  email: string;
  passwordHash: string | null;
  displayName: string;
};

/** In-memory shape of a `UserIdentity` row. Mirrors the entity's columns. */
export type InMemoryIdentity = {
  id: string;
  userId: string;
  provider: string;
  subject: string;
  email: string;
};

/**
 * Minimal `Repository<T>` surface used by `OAuthService`.
 *
 * `findOne` returns the first row matching ALL key/value pairs in `where`.
 * If `relations.user` is true and the row has a `userId` (i.e. it's an
 * identity), the matching user is attached under the `user` property to
 * mirror TypeORM's `relations: { user: true }` behavior — the service
 * relies on this when returning a returning-Google user.
 */
export type InMemoryRepo<T extends { id: string }> = {
  rows: T[];
  findOne: (opts: {
    where: Partial<T>;
    relations?: Record<string, boolean>;
  }) => Promise<T | null>;
  create: (data: Partial<T>) => T;
  save: (entity: T) => Promise<T>;
};

/**
 * The user rows are attached to identities in the same fixture, so
 * `makeRepo` needs read access to the user table when it resolves the
 * `relations.user` join. We expose the user rows on `globalThis` (set
 * by the test file before the service is imported) so the join works
 * without coupling this helper to a specific test.
 */
declare global {
  var __inMemoryUsers: InMemoryUser[] | undefined;
}

export function makeRepo<T extends { id: string }>(rows: T[]): InMemoryRepo<T> {
  return {
    rows,
    async findOne({ where, relations }) {
      const match = rows.find((row) =>
        Object.entries(where).every(
          ([key, value]) => (row as Record<string, unknown>)[key] === value,
        ),
      );
      if (!match) {
        return null;
      }
      if (relations?.user) {
        const userRows = globalThis.__inMemoryUsers;
        if (userRows) {
          const userId = (match as unknown as InMemoryIdentity).userId;
          const user = userRows.find((u) => u.id === userId);
          if (user) {
            (match as unknown as { user: InMemoryUser }).user = user;
          }
        }
      }
      return match;
    },
    create(data) {
      // `id` is auto-generated by TypeORM's PrimaryGeneratedColumn('uuid');
      // a missing id means "new row" — synthesize one so `save` can store it.
      return { ...(data as T), id: (data as { id?: string }).id ?? randomUUID() };
    },
    async save(entity) {
      const existingIdx = rows.findIndex((r) => r.id === entity.id);
      if (existingIdx >= 0) {
        rows[existingIdx] = entity;
      } else {
        rows.push(entity);
      }
      return entity;
    },
  };
}

/** Convenience: build a fresh pair of user + identity repos and register
 *  the user rows on `globalThis` so identity→user joins resolve. */
export function makeOAuthRepos(initial?: {
  users?: InMemoryUser[];
  identities?: InMemoryIdentity[];
}): { userRepo: InMemoryRepo<InMemoryUser>; identityRepo: InMemoryRepo<InMemoryIdentity> } {
  const users = initial?.users ?? [];
  const identities = initial?.identities ?? [];
  globalThis.__inMemoryUsers = users;
  return {
    userRepo: makeRepo<InMemoryUser>(users),
    identityRepo: makeRepo<InMemoryIdentity>(identities),
  };
}

/** The `User` / `UserIdentity` class references are unused at runtime
 *  in the in-memory repos, but the import keeps the `tsc` boundary
 *  happy and serves as a documentation breadcrumb: this helper mirrors
 *  those two entities' column shapes. */
export type _EntityRef = User | UserIdentity;
