{{- if .Values.devMode.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doschei.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_HOSTNAME: {{ printf "%s-postgres" (include "doschei.fullname" .) | quote }}
  DB_PORT: {{ .Values.postgres.service.port | quote }}
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_DATABASE_NAME: "doschei"
  JWT_SECRET: {{ include "doschei.backendEnvValue" (dict "root" . "key" "JWT_SECRET") | quote }}
{{- end }}
