apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doschei.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-postgres:%v/%s" .Values.postgres.auth.username .Values.postgres.auth.password (include "doschei.fullname" .) .Values.postgres.service.port .Values.postgres.auth.database | quote }}
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | quote }}
