{{- if and .Values.dex.enabled .Values.devMode.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: doschei-dex-passwords
  labels:
    app.kubernetes.io/component: dex
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}
type: Opaque
stringData:
  passwords.yaml: |
    - email: "admin@doschei.local"
      # nosemgrep: generic.secrets.security.detected-bcrypt-hash.detected-bcrypt-hash
      hash: "$2y$10$Xy26gXVo.7fVwsveB5HQNO5s8JPyxrMqwTdaGGW5rHaNF9G1gK8bG"
      username: "admin"
      userID: "0838b7b3-8e9c-4b9c-9c9c-9c9c9c9c9c9c"
  client-secret: "doschei-dev-secret"
{{- end }}
