namespace: doschei
fullnameOverride: doschei

devMode:
  enabled: false

defaultPodOptions: {}

imagePullSecrets: []

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/sthirs/doschei/frontend
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/sthirs/doschei/backend
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  env:
    PORT: "3000"
    NODE_ENV: production
    DB_SYNC: "false"
    SEED_ON_STARTUP: "false"
    AUTH_LOCAL_LOGIN_ENABLED: "true"
    AUTH_LOCAL_REGISTRATION_ENABLED: "true"
    CORS_ORIGIN: https://doschei.example.com
    FRONTEND_URL: ""
  secrets:
    jwt:
      secretName: doschei-backend-secrets
      key: JWT_SECRET
    database:
      secretName: doschei-backend-database
      keys:
        hostname: DB_HOSTNAME
        port: DB_PORT
        username: DB_USERNAME
        password: DB_PASSWORD
        databaseName: DB_DATABASE_NAME
    oauth:
      secretName: doschei-backend-oauth
      keys:
        config: OAUTH_CONFIG
        stateSecret: OAUTH_STATE_SECRET

ingress:
  enabled: true
  className: nginx
  host: doschei.example.com
  annotations: {}
  tls:
    enabled: false
    host: ""
    secretName: ""

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    secretName: doschei-postgres-auth
    keys:
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
      database: POSTGRES_DB
  persistence:
    enabled: false

dex:
  enabled: false
  image:
    repository: dexidp/dex
    tag: "v2.45.1@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5556
    targetPort: 5556
  config:
    issuer: http://doschei-dex.doschei.svc.cluster.local:5556/dex
    storage:
      type: sqlite3
      config:
        file: /var/dex/dex.db
    web:
      http: 0.0.0.0:5556
    staticClients:
      - id: doschei
        name: 'Do Schèi'
        secret: ${DOSCHEI_OAUTH_CLIENT_SECRET}
        redirectURIs:
          - 'http://doschei.127.0.0.1.nip.io/api/auth/oauth/callback'
    enablePasswordDB: true
