name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "*"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@6da19dd4ad4907e7a462b2dcef8ff53fa00de47e # main
    secrets: inherit
